services:
    laminas:
        container_name: laminas_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        env_file:
            - .env
        volumes:
            - .:/var/www
        depends_on:
            - db
    db:
        container_name: db
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
